# Docker Compose Configuration

version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./static/photos:/app/static/photos
      - ./static/responsive:/app/static/responsive
